version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/libghostty-wasm-demo"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    versioning-strategy: increase
